### ISSUE TITLE
PoolCollections.GCL.r subsetting attributes

### ISSUE THREAD

**Issue by csjalbert** [krshedd/GCL-R-Scripts#57]
Hey @awbarclay and @krshedd, 

PoolCollections grabs attributes using `my.gcl[ , 1:19]`. Is there a reason (e.g., other functions will crash) to limit to 1:19, in that order? I am wondering if we can select everything that is not in `loci`, perhaps just ditch the few lines with `attr` [83-84], from the function and change 86-88 to: 
` my.gcl %>% 
      dplyr::filter(FK_FISH_ID %in% IDs[[collection]]) %>% 
      dplyr::select(tidyselect::everything(), tidyselect::all_of(SubsetLoci))`

Note that the change is the first select, from all_of(attr) to everything() - Also, I am not sure if that will work but just wanted to get an example of the idea before I started changing things.

**Comment by krshedd** [comment]
Hey Chase,

I think Andy wrote it that way to make sure it was robust enough to pool a wide variety of collections, because they should ALL have those 19 columns. I’m open to your suggested change, but you’ll want to make sure that it works if you try to pool two+ collections with different attributes (i.e. some have stat_week, age, CWT, otolith, etc. and some do not).

Kyle

From: Chase Jalbert ***@***.***>
Sent: Tuesday, July 6, 2021 10:22 AM
To: krshedd/GCL-R-Scripts ***@***.***>
Cc: Shedd, Kyle R (DFG) ***@***.***>; Mention ***@***.***>
Subject: [krshedd/GCL-R-Scripts] PoolCollections.GCL.r subsetting attributes (#57)


Hey @awbarclay<https://urldefense.com/v3/__https:/github.com/awbarclay__;!!J2_8gdp6gZQ!7G1GbxFJd1tr3i_rwxauU_eaUP_ELgwTFNEL0AkS3GpdIU7dVO07q-z5bcftaepOqKj1$> and @krshedd<https://urldefense.com/v3/__https:/github.com/krshedd__;!!J2_8gdp6gZQ!7G1GbxFJd1tr3i_rwxauU_eaUP_ELgwTFNEL0AkS3GpdIU7dVO07q-z5bcftadppbilF$>,

PoolCollections grabs attributes using my.gcl[ , 1:19]. Is there a reason (e.g., other functions will crash) to limit to 1:19, in that order? I am wondering if we can select everything that is not in loci, perhaps just ditch the few lines with attr [83-84], from the function and change 86-88 to:
my.gcl %>% dplyr::filter(FK_FISH_ID %in% IDs[[collection]]) %>% dplyr::select(tidyselect::everything(), tidyselect::all_of(SubsetLoci))

Note that the change is the first select, from all_of(attr) to everything() - Also, I am not sure if that will work but just wanted to get an example of the idea before I started changing things.

**Comment by csjalbert** [comment]
Thanks, Kyle - My other concern is the ordering of columns. For example, I had the sillysource column, but it was at the end. This allowed poolcollections to work, but I had the wrong thing in column 19. Perhaps it's best to just make sure your inputs are correct... or maybe just check the first 19 colnames?


________________________________

**Comment by krshedd** [comment]
Ya, I agree, as a rule I do NOT like sub-setting by position (i.e. [, 1:19]). I like your suggestion to check the first 19 colnames, that seems prudent.
Kyle

**Comment by awbarclay** [comment]
Yes, it would be good to check the colnames.   Maybe the attr object, assigned on lines 83 and 84, should be hard coded to the legal attribute names. That way the function will select only those columns and in the correct order.  
Andy

**Comment by csjalbert** [comment]
That sounds good, Andy. I just did this and ran a test with SillySource as the last column in a few gcls – it works as expected, so will close it out and push changes. I didn’t incorporate different attributes as they can be added after.

Chase Jalbert
(907)267-2204
